/* Auto-generated by genmsg_cpp for file /home/egor/dnepr_quadro_control/msg/FlightDirection.msg */
#ifndef DNEPR_QUADRO_CONTROL_MESSAGE_FLIGHTDIRECTION_H
#define DNEPR_QUADRO_CONTROL_MESSAGE_FLIGHTDIRECTION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace dnepr_quadro_control
{
template <class ContainerAllocator>
struct FlightDirection_ {
  typedef FlightDirection_<ContainerAllocator> Type;

  FlightDirection_()
  : header()
  , dx(0)
  , dy(0)
  , height(0)
  , yaw(0)
  {
  }

  FlightDirection_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , dx(0)
  , dy(0)
  , height(0)
  , yaw(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int32_t _dx_type;
  int32_t dx;

  typedef int32_t _dy_type;
  int32_t dy;

  typedef int32_t _height_type;
  int32_t height;

  typedef int32_t _yaw_type;
  int32_t yaw;


  typedef boost::shared_ptr< ::dnepr_quadro_control::FlightDirection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dnepr_quadro_control::FlightDirection_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct FlightDirection
typedef  ::dnepr_quadro_control::FlightDirection_<std::allocator<void> > FlightDirection;

typedef boost::shared_ptr< ::dnepr_quadro_control::FlightDirection> FlightDirectionPtr;
typedef boost::shared_ptr< ::dnepr_quadro_control::FlightDirection const> FlightDirectionConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::dnepr_quadro_control::FlightDirection_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::dnepr_quadro_control::FlightDirection_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace dnepr_quadro_control

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::dnepr_quadro_control::FlightDirection_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::dnepr_quadro_control::FlightDirection_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::dnepr_quadro_control::FlightDirection_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0ee936a7284edff58f94a8b85615a024";
  }

  static const char* value(const  ::dnepr_quadro_control::FlightDirection_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0ee936a7284edff5ULL;
  static const uint64_t static_value2 = 0x8f94a8b85615a024ULL;
};

template<class ContainerAllocator>
struct DataType< ::dnepr_quadro_control::FlightDirection_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dnepr_quadro_control/FlightDirection";
  }

  static const char* value(const  ::dnepr_quadro_control::FlightDirection_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::dnepr_quadro_control::FlightDirection_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#Команды управления от управляющего модуля\n\
Header header\n\
#направление движения базы в плоскости, параллельной полу относительно текущего направления\n\
	int32 dx\n\
	int32 dy\n\
#желательная высота полета в сантиметрах\n\
	int32 height\n\
#поворот базы относительно текущего направления в градусах\n\
	int32 yaw\n\
	\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::dnepr_quadro_control::FlightDirection_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::dnepr_quadro_control::FlightDirection_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::dnepr_quadro_control::FlightDirection_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::dnepr_quadro_control::FlightDirection_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.dx);
    stream.next(m.dy);
    stream.next(m.height);
    stream.next(m.yaw);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct FlightDirection_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dnepr_quadro_control::FlightDirection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::dnepr_quadro_control::FlightDirection_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "dx: ";
    Printer<int32_t>::stream(s, indent + "  ", v.dx);
    s << indent << "dy: ";
    Printer<int32_t>::stream(s, indent + "  ", v.dy);
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
    s << indent << "yaw: ";
    Printer<int32_t>::stream(s, indent + "  ", v.yaw);
  }
};


} // namespace message_operations
} // namespace ros

#endif // DNEPR_QUADRO_CONTROL_MESSAGE_FLIGHTDIRECTION_H

