/* Auto-generated by genmsg_cpp for file /home/egor/dnepr_quadro_control/msg/RawArduinoControl.msg */
#ifndef DNEPR_QUADRO_CONTROL_MESSAGE_RAWARDUINOCONTROL_H
#define DNEPR_QUADRO_CONTROL_MESSAGE_RAWARDUINOCONTROL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace dnepr_quadro_control
{
template <class ContainerAllocator>
struct RawArduinoControl_ {
  typedef RawArduinoControl_<ContainerAllocator> Type;

  RawArduinoControl_()
  : header()
  , RawYaw(0)
  , RawPitch(0)
  , RawRoll(0)
  , RawThrottle(0)
  {
  }

  RawArduinoControl_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , RawYaw(0)
  , RawPitch(0)
  , RawRoll(0)
  , RawThrottle(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int32_t _RawYaw_type;
  int32_t RawYaw;

  typedef int32_t _RawPitch_type;
  int32_t RawPitch;

  typedef int32_t _RawRoll_type;
  int32_t RawRoll;

  typedef int32_t _RawThrottle_type;
  int32_t RawThrottle;


  typedef boost::shared_ptr< ::dnepr_quadro_control::RawArduinoControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dnepr_quadro_control::RawArduinoControl_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct RawArduinoControl
typedef  ::dnepr_quadro_control::RawArduinoControl_<std::allocator<void> > RawArduinoControl;

typedef boost::shared_ptr< ::dnepr_quadro_control::RawArduinoControl> RawArduinoControlPtr;
typedef boost::shared_ptr< ::dnepr_quadro_control::RawArduinoControl const> RawArduinoControlConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::dnepr_quadro_control::RawArduinoControl_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::dnepr_quadro_control::RawArduinoControl_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace dnepr_quadro_control

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::dnepr_quadro_control::RawArduinoControl_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::dnepr_quadro_control::RawArduinoControl_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::dnepr_quadro_control::RawArduinoControl_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9c8c3f3b492069e63a64a5b2af7296f8";
  }

  static const char* value(const  ::dnepr_quadro_control::RawArduinoControl_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x9c8c3f3b492069e6ULL;
  static const uint64_t static_value2 = 0x3a64a5b2af7296f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::dnepr_quadro_control::RawArduinoControl_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dnepr_quadro_control/RawArduinoControl";
  }

  static const char* value(const  ::dnepr_quadro_control::RawArduinoControl_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::dnepr_quadro_control::RawArduinoControl_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#команды управления, отправляемые напрямую на Ардуино\n\
Header header\n\
	int32 RawYaw\n\
	int32 RawPitch\n\
	int32 RawRoll\n\
	int32 RawThrottle\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::dnepr_quadro_control::RawArduinoControl_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::dnepr_quadro_control::RawArduinoControl_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::dnepr_quadro_control::RawArduinoControl_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::dnepr_quadro_control::RawArduinoControl_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.RawYaw);
    stream.next(m.RawPitch);
    stream.next(m.RawRoll);
    stream.next(m.RawThrottle);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct RawArduinoControl_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dnepr_quadro_control::RawArduinoControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::dnepr_quadro_control::RawArduinoControl_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "RawYaw: ";
    Printer<int32_t>::stream(s, indent + "  ", v.RawYaw);
    s << indent << "RawPitch: ";
    Printer<int32_t>::stream(s, indent + "  ", v.RawPitch);
    s << indent << "RawRoll: ";
    Printer<int32_t>::stream(s, indent + "  ", v.RawRoll);
    s << indent << "RawThrottle: ";
    Printer<int32_t>::stream(s, indent + "  ", v.RawThrottle);
  }
};


} // namespace message_operations
} // namespace ros

#endif // DNEPR_QUADRO_CONTROL_MESSAGE_RAWARDUINOCONTROL_H

