/* Auto-generated by genmsg_cpp for file /home/egor/dnepr/RaspberryPi/tuc_pelican/kinect_utils/msg/kinectPose.msg */
#ifndef KINECT_UTILS_MESSAGE_KINECTPOSE_H
#define KINECT_UTILS_MESSAGE_KINECTPOSE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace kinect_utils
{
template <class ContainerAllocator>
struct kinectPose_ {
  typedef kinectPose_<ContainerAllocator> Type;

  kinectPose_()
  : header()
  , distance_left(0.0)
  , distance_right(0.0)
  , distance_floor(0.0)
  , distance_ceiling(0.0)
  , distance_front(0.0)
  , pitch(0.0)
  , roll(0.0)
  , yaw(0.0)
  {
  }

  kinectPose_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , distance_left(0.0)
  , distance_right(0.0)
  , distance_floor(0.0)
  , distance_ceiling(0.0)
  , distance_front(0.0)
  , pitch(0.0)
  , roll(0.0)
  , yaw(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _distance_left_type;
  float distance_left;

  typedef float _distance_right_type;
  float distance_right;

  typedef float _distance_floor_type;
  float distance_floor;

  typedef float _distance_ceiling_type;
  float distance_ceiling;

  typedef float _distance_front_type;
  float distance_front;

  typedef float _pitch_type;
  float pitch;

  typedef float _roll_type;
  float roll;

  typedef float _yaw_type;
  float yaw;


  typedef boost::shared_ptr< ::kinect_utils::kinectPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinect_utils::kinectPose_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct kinectPose
typedef  ::kinect_utils::kinectPose_<std::allocator<void> > kinectPose;

typedef boost::shared_ptr< ::kinect_utils::kinectPose> kinectPosePtr;
typedef boost::shared_ptr< ::kinect_utils::kinectPose const> kinectPoseConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::kinect_utils::kinectPose_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::kinect_utils::kinectPose_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace kinect_utils

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::kinect_utils::kinectPose_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::kinect_utils::kinectPose_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::kinect_utils::kinectPose_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1e343b93fdaf868448ae493a3ee4a6e5";
  }

  static const char* value(const  ::kinect_utils::kinectPose_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1e343b93fdaf8684ULL;
  static const uint64_t static_value2 = 0x48ae493a3ee4a6e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::kinect_utils::kinectPose_<ContainerAllocator> > {
  static const char* value() 
  {
    return "kinect_utils/kinectPose";
  }

  static const char* value(const  ::kinect_utils::kinectPose_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::kinect_utils::kinectPose_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float32 distance_left\n\
float32 distance_right\n\
float32 distance_floor\n\
float32 distance_ceiling\n\
float32 distance_front\n\
float32 pitch\n\
float32 roll\n\
float32 yaw\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::kinect_utils::kinectPose_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::kinect_utils::kinectPose_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::kinect_utils::kinectPose_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::kinect_utils::kinectPose_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.distance_left);
    stream.next(m.distance_right);
    stream.next(m.distance_floor);
    stream.next(m.distance_ceiling);
    stream.next(m.distance_front);
    stream.next(m.pitch);
    stream.next(m.roll);
    stream.next(m.yaw);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct kinectPose_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinect_utils::kinectPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::kinect_utils::kinectPose_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "distance_left: ";
    Printer<float>::stream(s, indent + "  ", v.distance_left);
    s << indent << "distance_right: ";
    Printer<float>::stream(s, indent + "  ", v.distance_right);
    s << indent << "distance_floor: ";
    Printer<float>::stream(s, indent + "  ", v.distance_floor);
    s << indent << "distance_ceiling: ";
    Printer<float>::stream(s, indent + "  ", v.distance_ceiling);
    s << indent << "distance_front: ";
    Printer<float>::stream(s, indent + "  ", v.distance_front);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};


} // namespace message_operations
} // namespace ros

#endif // KINECT_UTILS_MESSAGE_KINECTPOSE_H

